version: 2

test:
  dependencies:
    post:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
  pre:
    - ./cc-test-reporter before-build
  post:
    - ./cc-test-reporter after-build --exit-code $EXIT_CODE

jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    environment:
      CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "test-results/jest/results.xml"
      - store_test_results:
          path: test-results
